# Usar uma imagem leve do Node.js
FROM node:18-alpine

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Copiar o arquivo de dependências
COPY package.json ./

# Instalar as dependências
RUN npm install

# Copiar o restante dos arquivos do projeto
COPY . .

# Expor a porta 80 (Padrão web)
EXPOSE 80

# Comando para iniciar a aplicação
CMD ["npm", "run", "dev"]